server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka # 集群版
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版
    register-with-eureka: true

spring:
  application:
    name: cloud-consumer-hystrix-order

# 设置调用的时长，默认是一秒钟
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000


# 日志配置
logging:
  level:
    com.wb.cloud.service.PaymentFeignService: debug

# 如果处理自身的容错就开启 。 开启方式与生产端不一 样 。
feign:
  hystrix:
    enabled: true
